#Michael-Patrick English
#makefile
#this is my make file for Project

CXXFLAGS=-std=c++11 -O3 -Wall
CXX=/usr/bin/g++ $(CXXFLAGS)

all:
	$(CXX) prob001.cpp -o prob001
	$(CXX) prob002.cpp -o prob002
	$(CXX) prob003.cpp -o prob003
	$(CXX) prob004.cpp -L/usr/local/lib64/stdlibc++ -o prob004
	$(CXX) prob005.cpp -o prob005
	$(CXX) prob006.cpp -o prob006
	$(CXX) prob007.cpp -o prob007
	$(CXX) prob008.cpp -o prob008
	$(CXX) prob009.cpp -o prob009
	$(CXX) prob010.cpp -o prob010
	$(CXX) prob011.cpp -o prob011
	$(CXX) prob012.cpp -o prob012
	$(CXX) prob014.cpp -o prob014
	$(CXX) prob015.cpp -o prob015
	$(CXX) prob021.cpp -o prob021
