/*
Michael-Patrick English
November 22, 2015
Project Euler Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include	<stdlib.h>
#include	<stdio.h>

int main(int argc, char** argv)
{

unsigned fib0 = 0, fib1 = 1;
unsigned tmp = fib1 + fib0;

long sum = 0;


while( tmp < 4000000 )
	{
	
	if ( tmp % 2 == 0)
		{
		sum += tmp;
		}
	
	fib0 = fib1;
	fib1 = tmp;

	tmp = fib1 + fib0;

	}
	
printf("%li\n",sum);

}


